# Generated by Django 2.1.4 on 2019-12-02 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_image_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_trail',
            name='image_uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
