# Generated by Django 2.1.4 on 2019-12-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_image_trail_image_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_trail',
            name='image_path',
            field=models.ImageField(upload_to='images'),
        ),
    ]
